language: generic

dist: focal
os: linux

env:
  jobs:
    # - EMACS_VERSION=26
    - EMACS_VERSION=27
    - EMACS_VERSION=master

before_install:
  - curl -LO "https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-$EMACS_VERSION.tar.gz"
  - tar -xaf "emacs-bin-$EMACS_VERSION.tar.gz" -C /
  - export PATH="/tmp/emacs/bin:${PATH}"
  - emacs --version
  - git clone --depth=1 https://github.com/cask/cask.git "$HOME/.cask"
  - export PATH="$HOME/.cask/bin:${PATH}"

install:
  - cask install

script:
  - cask exec ert-runner

notifications:
  email:
    on_success: never
    on_failure: always
